spring:
    cloud:
        config:
            uri: http://k8s-config-server

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

k8s:
  service1:
    link: http://k8s-service1
            
developer:
  details:
    name: Habeeb Okunade
    email: habeebcycle@gmail.com
    phone: +234-803-835-0075
