spring:
    cloud:
        config:
            uri: http://localhost:8888

eureka:
    client:
        service-url:
            default-zone: http://ip172-18-0-86-bpe8uoic687g00bd8rc0-8761.direct.labs.play-with-docker.com/eureka

habeebcycle:
    k8s:
        service1:
            link: http://localhost:9090
