spring:
    cloud:
        config:
            uri: http://k8s-config-server

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

habeebcycle:
    k8s:
        service1:
            link: http://k8s-service1
