## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/JbkG0hciJu?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: JbkG0hciJu
    password: IidjpHnQnf
    initialization-mode: always         # Initialize the datasource with available DDL and DML scripts
    
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
